### ISSUE TITLE
Do you know if anyone is doing a modern re-make of K240?

### ISSUE THREAD

**Issue by setherith** [tetracorp/k240#10]
Hi @tetracorp,

You've done some amazing work on reverse engineering K240, and I was wondering if you knew of any groups that were attempting to recreate the game for modern systems? 

I've been planning to build the game as close to the original for over a couple of years now, I have some of the assets designed in Blender already and some sound files from a decent voice synth that sounds very close to the original.

Having recently discovered your work I'm now planning the models / classes and how the game mechanics will hang together. Let me know if you're interested and I'll host what I have. I'm currently looking to build it in Python using Ursina game engine, but not adverse to changing if someone has something in progress already...

Thanks again, 

Shane

**Comment by tetracorp** [comment]
The most notable K240 remake project is [Sector 53](https://www.hollettgaming.com/project/1/Sector53/), which is currently in development. I've seen one or two other projects but they never made it past the very early stages. It's easy to underestiamte the amount of work that goes into making a game.

The main challenge is that K240 has a lot of game mechanics that aren't immediately obvious (hence this project), including some that are still not well understood. For example, the AI routines aren't well-understood, which would make it difficult to recreate the game with perfect accuracy.

**Comment by setherith** [comment]
Thanks again for the information, Sector 53 looks interesting, I'll follow their project for updates!

I'm trying to achieve the same aesthetics as the original, and using your information I'm hoping to get as close as possible to the original game play. Here's a tease at what I have so far...

![image](https://user-images.githubusercontent.com/11996394/206422522-d4d1f378-088c-433a-9a27-fa11412dc4d3.png)

If you fancy a look at the code it can be found here: https://github.com/setherith/k240
